---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample: Create an Amazon EC2 instance running the Amazon Linux AMI. This example creates an EC2 security group for the instance to give you SSH access."

Parameters:
  MyKeyName:
    Description: "Select The Key Name From The List."
    Type: AWS::EC2::KeyPair::KeyName

  MyEnvironment:
    Description: Select Your Environment
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Prod

  MyInstanceType: 
    Description: "WebServer EC2 instance type"
    Type: String
    Default: "t2.micro"
    AllowedValues: 
      - "t2.nano"
      - "t2.micro"
      - "t2.small"
      - "t2.medium"
      - "t2.large"

  MyAvailabilityZone:
    Description: Select the Availability Zone from the List
    Type: String
    Default: ap-south-1a
    AllowedValues:
      - ap-south-1a
      - ap-south-1b
      - ap-south-1c

  MySecurityGroups:
    Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
    Type: List<AWS::EC2::SecurityGroup::Id>	

  SecurityGroupIngressCIDR:
    Description: The IP address range that can be used to communicate to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  MySubnetId:
    Description: Select Subnet From The List.
    Type: AWS::EC2::Subnet::Id

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref MyAvailabilityZone
      ImageId: ami-0e306788ff2473ccb
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroupIds: !Ref MySecurityGroups
      SubnetId: !Ref MySubnetId
      Tags: 
        - Key: "Name"
          Value: "CFInstance"
        - Key: Environment
          Value: !Ref MyEnvironment		
      Tenancy: default

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      GroupName: "SSH-SG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SecurityGroupIngressCIDR

Outputs:
  EC2InstanceID:
    Description: Instance ID of Created Instance
    Value: !Ref MyEC2Instance

  AZ:
    Description: Instance ID of Created Instance
    Value: !GetAtt [MyEC2Instance, AvailabilityZone]

  PublicDNS:
    Description: Instance ID of Created Instance
    Value: !GetAtt [MyEC2Instance, PublicDnsName]

  PublicIp:
    Description: Instance ID of Created Instance
    Value: !GetAtt [MyEC2Instance, PublicIp]