---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This Cloud Formation Template will create Internet facing Classic Load Balancer with Listener port 80 with default health check settings"

Parameters:
  MySubnetId:
    Description: Select Subnet From The List.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  MyClassicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      SecurityGroups: 
        - !ImportValue ELBSecurityGroup
      Subnets: !Ref MySubnetId
      Tags: 
        - Key: Name
          Value: WebCLB
      CrossZone: true
      Instances: [!ImportValue MyInstance1, !ImportValue MyInstance2]

Outputs:
  CLBURL:
    Description: URL of the website
    Value: !Join ['', ['http://', !GetAtt [MyClassicLoadBalancer, DNSName]]]  