---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Cloud Formation"

Parameters:
  VPCId:
    Description: Select the VPC containing the instances
    Type: AWS::EC2::VPC::Id

  MySecurityGroup:
    Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
    Type: AWS::EC2::SecurityGroup::Id
  
  MySubnetId:
    Description: Select Subnet From The List.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true 
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Matcher: 
        HttpCode: '200'
      Name: WebTG
      Port: 80
      Protocol: TCP
      Tags:
        - Key: Name
          Value: WebTG
      TargetGroupAttributes: 
        - Key: deregistration_delay.timeout_seconds
          Value: 300
      TargetType: instance
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPCId
      Targets: 
        - Id: !ImportValue MyInstance1
          Port: 80
        - Id: !ImportValue MyInstance2
          Port: 80

  MyAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: WebNLB
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref MySecurityGroup
      Subnets: !Ref MySubnetId
      Tags: 
        - Key: Name
          Value: WebNLB
      Type: network
  
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward 
          TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref MyAppLoadBalancer
      Port: 80
      Protocol: TCP 

Outputs:
  ALBURL:
    Description: URL of the website
    Value: !Join ['', ['http://', !GetAtt [MyAppLoadBalancer, DNSName]]]