---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This Cloud Formation Template will create Internet facing Network Load Balancer with Listener port 80(TCP) and Target group forwarding traffic on 80(TCP) port with default health check settings"

Parameters:
  VPCId:
    Description: Select the VPC containing the instances
    Type: AWS::EC2::VPC::Id

  MySecurityGroup:
    Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
    Type: AWS::EC2::SecurityGroup::Id
  
  MySubnetId:
    Description: Select Subnet From The List.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true 
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 6
      HealthyThresholdCount: 3
      Name: WebTG
      Port: 80
      Protocol: TCP
      Tags:
        - Key: Name
          Value: WebTG
      TargetGroupAttributes: 
        - Key: deregistration_delay.timeout_seconds
          Value: 300
      TargetType: instance
      UnhealthyThresholdCount: 3
      VpcId: !Ref VPCId

  MyNetLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: WebNLB
      Scheme: internet-facing
      Subnets: !Ref MySubnetId
      Tags: 
        - Key: Name
          Value: WebNLB
      Type: network
  
  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward 
          TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref MyNetLoadBalancer
      Port: 80
      Protocol: TCP 

Outputs:
  NLBURL:
    Description: URL of the website
    Value: !Join ['', ['http://', !GetAtt [MyNetLoadBalancer, DNSName]]]